[tool.poetry]

name = "solvent"
version = "22.01.26" # <year>.<month>.<day>[.post<build>]
description = "Kills off fake grass."
authors = ["Solvent <solvent@example.com>"]
license = "MIT"

[tool.poetry.dependencies]

python = "^3.7"

pomace = "~0.9.1"
# pomace = { path = "../pomace", develop = true }

caffeine = { version = "~0.5", platform = "darwin" }
typer = "~0.4"

[tool.poetry.dev-dependencies]

autoflake = "^1.3.1"
black = "=20.8b1"
isort = "=5.8.0"
mypy = "~0.900"

[tool.isort]

profile = "black"

[tool.mypy]

ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = true

cache_dir = ".cache/mypy/"

plugins = ["datafiles.plugins:mypy"]

[tool.poetry.scripts]

solvent = "solvent:main"

[build-system]

requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

