[tool.poetry]
name = "texas"
version = "0.0.2"
description = "テキサスホールデムのpython実装です"
authors = ["agarichan"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/agarichan/texas"

[tool.poetry.dependencies]
python = "^3.8"
rich = {version = "^11.1.0", optional = true}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
flake8 = "^4.0.1"
pyproject-flake8 = "^0.0.1-alpha.2"
pyright = "^0.0.13"
black = "^21.12b0"
ipykernel = "^6.7.0"
isort = "^5.10.1"

[tool.poetry.extras]
sample = ["rich"]

[tool.poetry-dynamic-versioning]
enable = false
style = "pep440"

[tool.poetry-dynamic-versioning.substitution]
files = ["src/*/__init__.py"]

[tool.flake8]
max-line-length = 120
ignore = "E226,E302,E203,E41,W503,E722,E731"
max-complexity = 10

[tool.black]
line-length = 120
exclude = '''
(
    .mypy_cache
    | .pytest_cache
    | .tox
    | .venv
    | dist
)
'''

[tool.isort]
line_length = 120
profile = "black"

[tool.pyright]
pythonVersion = "3.8"

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing:skip-covered --cov-report term --cov-report xml"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"