[tool.poetry]
name = "pypelinez"
version = "0.5.7"
description = ""
authors = ["thecb4 <cavelle@thecb4.io>"]
readme = "README.md"

# https://stackoverflow.com/questions/62572961/how-to-organize-a-python-project-with-poetry-for-a-command-line-script
[tool.poetry.scripts]
pypelinez = "pypelinez.main:main"

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.0.3"
colorama = "^0.4.4"
toml = "^0.10.2"
semantic-version = "^2.8.5"

# https://stackoverflow.com/questions/69528842/an-error-while-trying-to-execute-tests-on-python-3-10-with-pytest
[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
black = "^21.12b0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
indent_style = "space"
indent_size = 2
insert-final-newline = true
trim-trailing-whitespace = true
include = '\.pyi?$'

[tool.flake8]
max-line-length = 120
extend-ignore = "E203"

[tool.chuy]
format = "poetry run black ."
lint   = "poetry run flake8 ."
build  = "poetry build"
test   = "poetry run pytest"
submit-feature = "pypelinez feature add-commit && pypelinez feature request-merge"